# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly galleon plugins - CI

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  test-galleon-plugins:
    name: Build test Galleon Plugins
    # To fire 2
    uses: jfdenise/galleon-plugins/.github/workflows/testing-workflow.yml@fix-cache
    with:
      wildfly-ref: main